/**
 * Central icon registry — one consistent SVG family (Lucide) across the app.
 * Replaces emoji icons (Pro Max anti-pattern: no-emoji-icons).
 * Usage: <Icon name="trade" className="w-5 h-5" />
 */
import {
  LayoutDashboard,
  TrendingUp,
  Globe,
  Rocket,
  FileText,
  CreditCard,
  Calculator,
  Landmark,
  Coins,
  Package,
  Handshake,
  Trophy,
  Search,
  Menu,
  LogOut,
  MessageCircle,
  X,
  ArrowUpRight,
  Sparkles,
  ShieldCheck,
  Lock,
  BarChart3,
  Calendar,
  Ship,
  Flag,
  Download,
  ReceiptText,
  Boxes,
  ClipboardList,
  BadgeCheck,
  Banknote,
  Undo2,
  Percent,
  Target,
  TrendingDown,
  Plus,
  Minus,
  Check,
  MapPin,
  Mail,
  Phone,
  User,
  Building2,
  RotateCcw,
} from 'lucide-react'

const REGISTRY = {
  dashboard: LayoutDashboard,
  trade: TrendingUp,
  buyers: Globe,
  guide: Rocket,
  documents: FileText,
  payment: CreditCard,
  costing: Calculator,
  schemes: Landmark,
  credits: Coins,
  products: Package,
  handshake: Handshake,
  trophy: Trophy,
  search: Search,
  menu: Menu,
  logout: LogOut,
  chat: MessageCircle,
  close: X,
  arrow: ArrowUpRight,
  sparkles: Sparkles,
  shield: ShieldCheck,
  lock: Lock,
  chart: BarChart3,
  calendar: Calendar,
  ship: Ship,
  flag: Flag,
  download: Download,
  receipt: ReceiptText,
  boxes: Boxes,
  clipboard: ClipboardList,
  badgeCheck: BadgeCheck,
  banknote: Banknote,
  undo: Undo2,
  percent: Percent,
  target: Target,
  trendingDown: TrendingDown,
  plus: Plus,
  minus: Minus,
  check: Check,
  mapPin: MapPin,
  mail: Mail,
  phone: Phone,
  user: User,
  building: Building2,
  reset: RotateCcw,
}

export default function Icon({ name, className = 'w-5 h-5', strokeWidth = 1.75, ...props }) {
  const Cmp = REGISTRY[name]
  if (!Cmp) return null
  return <Cmp className={className} strokeWidth={strokeWidth} aria-hidden="true" {...props} />
}

export { REGISTRY }
